parameters:
  envia_client.class: Jplarar\EnviaBundle\Services\EnviaClient

services:
    Jplarar\EnviaBundle\Services\EnviaClient: "@envia_client"
    envia_client:
        class:     "%envia_client.class%"
        arguments: ["%envia_token%", "%envia_environment%"]
        autowire: true
        public: true